Eo 10
marcelogaray/auto-GA-v02 pull request #7
Opened 2018-06-18 12:42 UTC by lines17

Titulo: EO-10 Verificar que una posicion no puede ser creada si los campos requeridos no son llenados

2018-06-18 12:46 UTC, lines17 commented
TestCase:
![eo-01writtentc](https://user-images.githubusercontent.com/4944251/41536568-fab53dd2-72d3-11e8-8bbd-34fcc45e3ff2.png)

TestCase Passed:
![eo-01-testexecuted](https://user-images.githubusercontent.com/4944251/41536583-0972daa0-72d4-11e8-84be-664652579705.png)

2018-06-20 00:54 UTC, marcelogaray requested changes
review observation

2018-06-20 00:54 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Position/CreatePosition.java
> +    public void clickOnOrganizationalMenuOption(){
change to clickOrganizationalMenuOption

2018-06-20 00:54 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionCreatePosition.java
> +
remove blank line

2018-06-20 00:54 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionCreatePosition.java
> +
remove blank line

2018-06-20 00:54 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionCreatePosition.java
> +    public void iClickOnButton(String arg0) throws Throwable {
unused parameter, remove it.

2018-06-20 00:54 UTC, marcelogaray commented on src/test/resources/features/CreatePosition.feature
> +    And User is authenticated
use one step definitons to set credentials

2018-06-20 00:54 UTC, marcelogaray commented on src/test/resources/features/CreatePosition.feature
> +    And I click on "Estructura Organizacional" menu button
dont use "I"

2018-06-20 00:54 UTC, marcelogaray commented on src/test/resources/features/CreatePosition.feature
> +    And I click on "Estructura Organizacional" menu button
Example

According to the test case it should be:
Given I loging to 'SMARTHOUSE' page with properly credentials
When go to 'Estructura Organizacional' on 'Header' page
And navigate to 'Gerencia General' option on 'Dashboar/Left Panel/etc...' page
And click over 'Eliminar' button on 'Genencia General' page
Then 'Area Gerencia General' title should be displayed

2018-06-20 19:36 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionCreatePosition.java
> +        createPosition = new CreatePosition();
it dont need to be here.

2018-06-20 19:36 UTC, marcelogaray requested changes
review observations

2018-06-21 15:05 UTC, closed without merging